### ISSUE TITLE
Reorganize admin pages/tasks

### ISSUE THREAD

**Issue by vitoravelino** [SUSE/Portus#1766]
### Description

Currently admin pages are kinda confusing and not too useful. For example, an admin cannot create a team when they reach the teams admin page. The same happens for namespaces. The repositories page currently list all the repositories you have access instead of only your own (like we do for namespaces and teams).

Based on those issues, we decided to unify the admin tasks into the normal pages. So we will get rid of some admin pages and improve the rest 

- [x] Get rid of admin teams page and unify with normal teams page (via #1776)
- [X] Get rid of admin namespaces page and unify with normal namespaces page (via #1783)
- [x] Split repositories into "teams member repositories" and "other repositories" (via #1785)
- [x] Migrate admin dashboard overview elements (number of teams, namespaces, etc) to normal overview (via #1786)
- [x] Group recent activities into "personal" and "administrative" tabs or something similar (via #1786)
- [x] Show "users" sidebar item if admin (via #1784)
- [x] Show "registries" sidebar item if admin (via #1784)
