### ISSUE TITLE
Improve Integration Testing

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#745]
We have a private integration testing. This is far from ideal:

1. It should be re-written from scratch to handle multiple scenarios like LDAP and so on.
2. It should be open source so people that contribute to Portus can also update themselves integration tests.

## Tasks

- [x] Provide a bare setup with containers.
- [x] Write basic integration testing about pushing/pulling/login/etc with basic authentication.
- [x] LDAP: extend the previous point to handle multiple LDAP configurations.
- [x] Figure out if this can be done inside of Travis CI, or we should spin up a new Jenkins dedicated job for this (and hook it up into Github).
